"""Firestore document models for GO Documents.

Database: go-documents (asia-southeast1)
Collection: document-records
Running code format: AQ-26XXX (year prefix + 3-digit running number)

Live URL: docs.leka.studio/<document_type>/<doc_id>
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


# ----------------------------------------------------------------------
# Enums
# ----------------------------------------------------------------------

BASE_URL = "https://docs.leka.studio"

DOCUMENT_TYPE_PATHS = {
    "quotation": "quotations",
    "submission": "submissions",
    "datasheet": "datasheets",
    "certificate": "certificates",
}


def make_document_url(document_type: str, doc_id: str) -> str:
    """Generate the live URL for a document record."""
    path = DOCUMENT_TYPE_PATHS.get(document_type, document_type + "s")
    return f"{BASE_URL}/{path}/{doc_id}"


class DocumentType(str, Enum):
    QUOTATION = "quotation"
    SUBMISSION = "submission"
    DATASHEET = "datasheet"
    CERTIFICATE = "certificate"


class QuotationStatus(str, Enum):
    DRAFT = "draft"
    SENT = "sent"
    REVISED = "revised"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    EXPIRED = "expired"
    CANCELLED = "cancelled"


class PaymentMilestone(str, Enum):
    DEPOSIT = "deposit"
    PRE_SHIPMENT = "pre_shipment"
    DELIVERY = "delivery"
    HANDOVER = "handover"


class Currency(str, Enum):
    THB = "THB"
    USD = "USD"
    EUR = "EUR"
    CNY = "CNY"
    GBP = "GBP"


# ----------------------------------------------------------------------
# Sub-models (embedded documents, not subcollections)
# ----------------------------------------------------------------------

class CustomerInfo(BaseModel):
    """Customer contact and billing information."""

    attn: str = ""
    company: str = ""
    address: str = ""
    tax_id: str = ""
    email: str = ""
    tel: str = ""


class ProposerInfo(BaseModel):
    """Sales rep / proposer information."""

    name: str = ""
    email: str = ""
    mobile: str = ""


class LineItem(BaseModel):
    """Single quotation line item."""

    item_no: int
    product_code: str = ""
    description: str = ""
    description_sub: str = ""          # material, dimensions, etc.
    unit: str = ""                     # set, pcs, sq.m., lot, etc.
    qty: float = 0.0
    unit_rate: float = 0.0            # in THB
    amount: float = 0.0               # qty * unit_rate
    category: str = ""                # section header group
    vendor: str = ""                  # source vendor/brand
    notes: str = ""


class AttachmentMeta(BaseModel):
    """Metadata for files stored in GCS."""

    file_name: str
    gcs_path: str                     # gs://bucket/path
    content_type: str                 # application/pdf, image/png, etc.
    size_bytes: int = 0
    uploaded_at: datetime = Field(default_factory=_utcnow)
    attachment_type: str = ""         # product_image, datasheet, warranty, generated_pdf


class ScheduleMilestone(BaseModel):
    """Estimated schedule milestone."""

    name: str                         # e.g., "Deposit Received", "Design Approval"
    duration_text: str = ""           # e.g., "7–14 days"
    target_date: datetime | None = None
    actual_date: datetime | None = None
    notes: str = ""


class PaymentTerm(BaseModel):
    """Payment term / installment."""

    payment_no: int
    percentage: float                 # e.g., 30.0
    milestone: str                    # e.g., "Deposit upon signing contract"
    amount: float = 0.0              # calculated from grand_total * percentage/100
    status: str = "pending"          # pending, invoiced, paid
    due_date: datetime | None = None
    paid_date: datetime | None = None
    invoice_no: str = ""


# ----------------------------------------------------------------------
# Main quotation document
# ----------------------------------------------------------------------

class AredaQuotation(BaseModel):
    """Root document in the document-records collection (go-documents DB).

    Database: go-documents (asia-southeast1)
    Collection: document-records
    Document ID: auto-generated by Firestore
    Quotation code: AQ-{YY}{NNN} — e.g., AQ-26001
    """

    # --- Document Type (for multi-type collection) ---
    document_type: str = "quotation"
    template_id: str = "areda-quotation"
    document_url: str = ""            # https://docs.leka.studio/quotations/<doc_id>

    # --- Identity ---
    quotation_code: str               # AQ-26001, AQ-26002, ...
    revision_no: int = 0
    status: QuotationStatus = QuotationStatus.DRAFT
    language: str = "en"              # en or th

    # --- Customer ---
    customer: CustomerInfo = Field(default_factory=CustomerInfo)

    # --- Project ---
    project_name: str = ""
    subject: str = ""

    # --- Proposer ---
    proposed_by: ProposerInfo = Field(default_factory=ProposerInfo)

    # --- Line Items ---
    items: list[LineItem] = Field(default_factory=list)
    categories: list[str] = Field(default_factory=list)  # ordered section headers

    # --- Financials ---
    currency: Currency = Currency.THB
    fx_rate: float = 1.0              # FX rate at time of quotation
    fx_base_currency: Currency = Currency.THB
    subtotal: float = 0.0
    vat_rate: float = 7.0             # percentage
    vat_amount: float = 0.0
    grand_total: float = 0.0
    discount_amount: float = 0.0
    discount_note: str = ""

    # --- Schedule ---
    schedule: list[ScheduleMilestone] = Field(default_factory=list)

    # --- Payment Terms ---
    payment_terms: list[PaymentTerm] = Field(default_factory=list)

    # --- Attachments ---
    attachments: list[AttachmentMeta] = Field(default_factory=list)
    generated_pdf: AttachmentMeta | None = None  # the final quotation PDF

    # --- Validity ---
    valid_days: int = 15              # quotation validity in days
    valid_until: datetime | None = None

    # --- Dates ---
    document_date: datetime = Field(default_factory=_utcnow)
    created_at: datetime = Field(default_factory=_utcnow)
    updated_at: datetime = Field(default_factory=_utcnow)
    sent_at: datetime | None = None
    accepted_at: datetime | None = None
    expired_at: datetime | None = None

    # --- Audit ---
    created_by: str = ""              # user email
    updated_by: str = ""
    revision_history: list[dict[str, Any]] = Field(default_factory=list)
    notes: str = ""                   # internal notes

    def to_firestore(self) -> dict[str, Any]:
        """Serialize to Firestore-compatible dict."""
        return self.model_dump(mode="json")


# ----------------------------------------------------------------------
# Counter document (for running number generation)
# ----------------------------------------------------------------------

class QuotationCounter(BaseModel):
    """Stored in areda_quotation_counters/{year} to track running numbers.

    Document ID: "2026", "2027", etc.
    """

    year: int
    last_number: int = 0              # last assigned running number
    updated_at: datetime = Field(default_factory=_utcnow)
