"""Firestore document models for Playground Safety Inspection Certificates.

Collection: document-records (shared with quotations)
Running code format: SO{YY}-{NNN} (year prefix + 3-digit running number)
Template ID: leka-playground-inspection
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


# ----------------------------------------------------------------------
# Enums
# ----------------------------------------------------------------------

class InspectionStatus(str, Enum):
    DRAFT = "draft"
    ISSUED = "issued"
    REVISED = "revised"
    EXPIRED = "expired"
    CANCELLED = "cancelled"


class ComplianceResult(str, Enum):
    SUBSTANTIAL_COMPLIANCE = "substantial_compliance"
    CORRECTIVE_ACTION = "corrective_action"


# ----------------------------------------------------------------------
# Sub-models
# ----------------------------------------------------------------------

class SiteInfo(BaseModel):
    """Playground site information."""

    playground_name: str = ""
    site_location: str = ""
    site_location_short: str = ""
    owner_operator: str = ""
    age_group: str = ""


class InspectorInfo(BaseModel):
    """CPSI inspector credentials."""

    name: str = "Eukrit Kraikosol"
    credential: str = "NRPA Certified Playground Safety Inspector (CPSI)"
    cpsi_cert_no: str = "64835-0801"
    cpsi_expiration: str = "08/01/2028"


class WarrantyPeriod(BaseModel):
    """Warranty period from handover date."""

    handover_date: datetime | None = None
    warranty_months: int = 12
    warranty_start: str = ""
    warranty_end: str = ""


class ClientInfo(BaseModel):
    """Client contact information."""

    attn: str = ""
    company: str = ""
    email: str = ""
    tel: str = ""


# ----------------------------------------------------------------------
# Main inspection certificate document
# ----------------------------------------------------------------------

class PlaygroundInspectionCertificate(BaseModel):
    """Root document in the document-records collection (go-documents DB).

    Database: go-documents (asia-southeast1)
    Collection: document-records
    Document ID: auto-generated by Firestore
    Report code: SO{YY}-{NNN} — e.g., SO25-023
    """

    # --- Document Type (for multi-type collection) ---
    document_type: str = "playground_inspection"
    template_id: str = "leka-playground-inspection"

    # --- Identity ---
    report_no: str                        # SO25-023, SO25-024, ...
    revision_no: int = 1                  # R1 = 1
    revision_label: str = "R1"            # Display label
    status: InspectionStatus = InspectionStatus.DRAFT
    language: str = "en"

    # --- Site ---
    site: SiteInfo = Field(default_factory=SiteInfo)

    # --- Client ---
    client: ClientInfo = Field(default_factory=ClientInfo)

    # --- Inspection ---
    inspection_date: datetime | None = None
    inspection_type: str = "Comprehensive Safety Inspection"
    reinspection_date: str = ""           # e.g., "March 2027"
    compliance_result: ComplianceResult = ComplianceResult.SUBSTANTIAL_COMPLIANCE

    # --- Warranty (R1 addition) ---
    warranty: WarrantyPeriod = Field(default_factory=WarrantyPeriod)

    # --- Inspector ---
    inspector: InspectorInfo = Field(default_factory=InspectorInfo)

    # --- Dates ---
    document_date: datetime = Field(default_factory=_utcnow)
    created_at: datetime = Field(default_factory=_utcnow)
    updated_at: datetime = Field(default_factory=_utcnow)
    issued_at: datetime | None = None

    # --- Audit ---
    created_by: str = ""
    updated_by: str = ""
    revision_history: list[dict[str, Any]] = Field(default_factory=list)
    notes: str = ""

    def to_firestore(self) -> dict[str, Any]:
        """Serialize to Firestore-compatible dict."""
        return self.model_dump(mode="json")
